version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-8)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - |
        docker build -t $REPOSITORY_URI:$IMAGE_TAG \
        --build-arg GEELBE_API_CLIENT_ID="$GEELBE_API_CLIENT_ID" \
        --build-arg GEELBE_API_CLIENT_SECRET="$GEELBE_API_CLIENT_SECRET" \
        --build-arg GEELBE_API_SCOPE="$GEELBE_API_SCOPE" \
        --build-arg GEELBE_API_PROTOCOL="$GEELBE_API_PROTOCOL" \
        --build-arg GEELBE_API_HOST="$GEELBE_API_HOST" \
        --build-arg GEELBE_FACEBOOK_APP_ID="$GEELBE_FACEBOOK_APP_ID" \
        --build-arg GEELBE_FACEBOOK_APP_SECRET="$GEELBE_FACEBOOK_APP_SECRET" \
        --build-arg S3_FOLDER="ventaspop-static/geelbe-web/$IMAGE_TAG/" \
        --build-arg AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" \
        --build-arg AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" \
        --build-arg PUBLIC_PATH="https://$STATIC_DOMAIN/geelbe-web/$IMAGE_TAG" .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing geelbe web ...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
